# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Documentation
    url: docs/
    weight: 20
  - name: Publications
    url: publications/
  #   weight: 30
  # - name: Showcase
  #   url: showcase/
  #   weight: 40
  # - name: Community
  #   url: community/
  #   weight: 50

sidebar:
  - identifier: DEVELOPMENT
    name: DEVELOPMENT
    params:
      type: separator
    weight: 1
  - identifier: Github
    name: "Github ↗"
    # pageRef: "/community"
    url: "https://github.com/CompSeismoUT/SpecFWAT"
    weight: 2
  - identifier: Contributors
    name: "Contributors ↗"
    url: "https://www.physics.utoronto.ca/~liuqy/"
    weight: 3
