name: Deploy website to GitHub Pages

env:
  WC_HUGO_VERSION: '0.136.5'

on:
  # Trigger the workflow every time you push to the `main` branch
  push:
    branches: ["main"]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Provide permission to clone the repo and deploy it to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Build website
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
          # Fetch history for Hugo's .GitInfo and .Lastmod
        fetch-depth: 0
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: ${{ env.WC_HUGO_VERSION }}
        extended: true
    - name: Build with Hugo
      env:
        HUGO_ENVIRONMENT: production
      run: |
        hugo --gc --minify -b https://specfwat.xumijian.me/
    # - name: Generate Pagefind search index
    #   run: npx pagefind --source "public"
    - name: Commit files
      run: |
        cd ./public
        echo "specfwat.xumijian.me" > CNAME
        git config --local user.email "gomijianxu@gmail.com"
        git config --local user.name "xumi1993"
        git add .
        git commit -m `date +"%Y.%m.%dT%H:%M%S"`
    - name: Pushes to blog repository
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: 'public'
        destination-github-username: 'xumi1993'
        destination-repository-name: 'SpecFWAT-docs'
        user-email: gomijianxu@gmail.com
        target-branch: gh-pages